version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: em-pg
    environment:
      POSTGRES_DB: grog
      POSTGRES_USER: simon
      POSTGRES_PASSWORD: simon5579!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U simon -d grog"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: backend
    ports:
      - "5579:5579"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: